version: v1.0
author: lhlyu
name: iyu
env: prod

jwt:
  secret: 3.14159265358979323
  itv: 86400 # jwt有效时长，单位秒

server:
  host: 0.0.0.0
  port: 8080
  limit: 15   # 每秒最多允许N个请求

log:
  level: debug
  out: libra.log

redis:
  addr: 127.0.0.1:6379
  password: 123456
  database: 0
  maxActive: 50
  idleTimeout: 60

redis_key:
  iyu: "iyu:"

db:
  db_wr:
    user: root
    password:
    host: 127.0.0.1
    port: 3306
    database: demo
    charset: utf8
    parseTime: true
    maxOpenConns: 1
    maxIdleConns: 3
    connMaxLifetime: 30

email:
  host: smtp.163.com
  port: 465
  user: 名字
  password: SMTP邮箱密码
  from: 负责发送消息的邮箱
  to: 接收消息的邮箱
  subject: 标题
